<?xml version="1.0" encoding="utf-8"?><Database Name="ERP" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DZEKX7NU0G5GWI8;Initial Catalog=ERP;Persist Security Info=True;User ID=sa" SettingsObjectName="Model.Properties.Settings" SettingsPropertyName="ERPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Config" Member="Config">
    <Type Name="Config">
      <Column Name="SignID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StyleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Examination" Member="Examination">
    <Type Name="Examination">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CheckID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PatID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CheckDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InMed" Member="InMed">
    <Type Name="InMed">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedBarCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Production" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ProduteDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedBid" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MedUnitPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Memary" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MedPlan" Member="MedPlan">
    <Type Name="MedPlan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoctorID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Useage" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OneTimeUse" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Days" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TimesUse" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SignID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StyleName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SpliteNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OutMed" Member="OutMed">
    <Type Name="OutMed">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedBarCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MedName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="LookDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DoctorID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MedUnitPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MedPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Useage" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OneTimeUse" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Days" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TimesUse" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SpliteNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prescription" Member="Prescription">
    <Type Name="Prescription">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DoctorID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Diagnosis" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="MedCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MedPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PastHistory" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Treatment" Member="Treatment">
    <Type Name="Treatment">
      <Column Name="SignID" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SignName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>